name: Shai Hulud Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    name: Security Scan for Shai Hulud 2.0 IOCs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git log analysis

      - name: Install dependencies
        run: |
          # Install optional tools for enhanced scanning
          sudo apt-get update
          sudo apt-get install -y coreutils

      - name: Run Shai Hulud Scanner
        id: scan
        run: |
          chmod +x ./scan.sh
          ./scan.sh . || exit_code=$?
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Upload scan report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: shai-hulud-scan-report
          path: shai-hulud-scan-report.txt
          retention-days: 90

      - name: Comment PR with results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('shai-hulud-scan-report.txt', 'utf8');

            const comment = `## 🛡️ Shai Hulud 2.0 Security Scan Results

            <details>
            <summary>Click to view full scan report</summary>

            \`\`\`
            ${report}
            \`\`\`

            </details>

            ---
            *Automated scan powered by [Shai Hulud Scanner](https://github.com/${{ github.repository }})*
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Fail if critical issues found
        if: steps.scan.outputs.exit_code == '1'
        run: |
          echo "::error::Critical security issues detected! Review the scan report."
          exit 1

      - name: Create issue if critical on main
        if: github.ref == 'refs/heads/main' && steps.scan.outputs.exit_code == '1'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('shai-hulud-scan-report.txt', 'utf8');

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 SECURITY: Shai Hulud 2.0 Indicators Detected',
              body: `## Critical Security Alert

              Shai Hulud 2.0 indicators of compromise have been detected in the main branch!

              **Immediate Actions Required:**
              1. Isolate affected systems
              2. Rotate all credentials (npm, GitHub, cloud)
              3. Review scan report below
              4. Remove malicious code
              5. Audit recent deployments

              ### Scan Report

              \`\`\`
              ${report}
              \`\`\`

              ### Resources
              - [DataDog Analysis](https://securitylabs.datadoghq.com/articles/shai-hulud-2.0-npm-worm/)
              - [IOC List](https://github.com/DataDog/indicators-of-compromise/tree/main/shai-hulud-2.0)
              - [npm Security](mailto:security@npmjs.com)
              `,
              labels: ['security', 'critical', 'supply-chain']
            });
